### ISSUE TITLE
Fixes to work in 2020

### ISSUE THREAD

**Issue by arduino12** [netanelf/bicycle_video_player#11]
**Hi,**

Please add `xautomation` to this [line](https://github.com/netanelf/bicycle_video_player/blob/master/install.sh#L11).
Also change `python` to `python2` [here](https://github.com/netanelf/bicycle_video_player/blob/master/run_main_controller.sh#L5)

Now it works :)

**Comment by netanelf** [comment]
done in: 
https://github.com/netanelf/bicycle_video_player/commit/d52936d15dd09d1c0a7dab6e071b43ad373f9d9b

BTW, if you prefer, you have write permissions to the repository
