### ISSUE TITLE
tour exhibit: fan should probably stop when the video stops

### ISSUE THREAD

**Issue by orlevi** [netanelf/bicycle_video_player#7]
not sure if this is addressed in the code but i think that it's not. 
it seems logical that the fan should stop and play with the video (when topography is downhill). we would not expect wind to blow when the bike is still.
load can stay as it is as it is directly connected to the pedaling...

**Comment by amirbs** [comment]
הי
כמו שכתבתי במייל הקודם - זה בעיה מסדר שני כרגע (אם המאורר יעבוד בזמן עצירה) הגיוני שאתה צודק אבל לא ממש קריטי ומה שחשוב זה לא לעשות שינויים בקוש שיסכנו את אמינות הריצה ומה שרואה המבקר.

אמיר ב

________________________________
מ: orlevi ‏[notifications@github.com]‏
‏‏נשלח: יום רביעי 05 יולי 2017 09:02
עד: netanelf/bicycle_video_player
‏‏עותק לידיעה: Subscribed
‏‏נושא: [netanelf/bicycle_video_player] tour exhibit: fan should probably stop when the video stops (#7)


not sure if this is addressed in the code but i think that it's not.
it seems logical that the fan should stop and play with the video (when topography is downhill). we would not expect wind to blow when the bike is still.
load can stay as it is as it is directly connected to the pedaling...

**Comment by netanelf** [comment]
fixed
